### ISSUE TITLE
Insight power notifications

### ISSUE THREAD

**Issue by chrisn-au** [hardillb/node-red-contrib-wemo-ng#10]
Thanks for a great package. Works well for switching on and off but I don't appear to be able to get regular updates on power usage. I would love a event notification every time there are power event notifications - (every couple of seconds)

Any pointers on where to look

**Comment by hardillb** [comment]
This code is obsolete, please use the node-red-node-wemo nodes from the node-red-nodes project. (https://github.com/node-red/node-red-nodes/tree/master/hardware/wemo)

This has better event subscription support but it still may drop from time to time

**Comment by chrisn-au** [comment]
Ben,

thanks, i updated and the same problem  - it looks like you are not getting
the messages as not subscribing to insightParams: '
urn:Belkin:service:insight:1' service.

I got this from https://github.com/timonreinhard/wemo-client

no problems if you have got better stuff to do I will hack it over the next
couple of weeks

The SOAP stuff is outside of any experience so a bit daunting.

Anything you can do to help would be appreciated


cheers

Chris Neave
