### ISSUE TITLE
Finds my Philips Hue Bridge, normal ?

### ISSUE THREAD

**Issue by natcl** [hardillb/node-red-contrib-wemo-ng#2]
The wemong node seems to discover my Philips Hue Bridge.  Is this normal ?

**Comment by hardillb** [comment]
They both use uPNP so it's not a total surprise, I'll try and have a look at the Hue node to see if I can work out how to filter it out for now. If not I think we have a couple of Hue bridges kicking round the office I may be able to borrow to have a play

**Comment by hardillb** [comment]
If not I can probably give you a bit of code to run that will get me all of the discovery information to work something out from
