### ISSUE TITLE
Discovery didn't work

### ISSUE THREAD

**Issue by Roaders** [hardillb/node-red-contrib-wemo-ng#5]
I'm new to node-red so it took me a while to get this installed but I eventually did and the extra nodes appeared in node-red.

Discovery doesn't seem to be working though, I have waited around 10 minutes and still nothing.

If I double click the node I see a dialogue with a drop down "Add new WeMoNG-dev..."
I click the little edit icon and I get another dialogue with nothing listed in the Device list.

What can I try to get this working?

**Comment by Roaders** [comment]
It seems that I didn't wait long enough... I also updated the firmware on the switch and now it can see it,

**Comment by glynhudson** [comment]
How long did you have to wait? I've also got this issue. Can I check the required ports are open? I've opened 1900 UDP:

`sudo ufw allow 1900/udp`

My Pi which is running nodered has the following posts open 

```
netstat -ntlp | grep LISTEN
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:1880            0.0.0.0:*               LISTEN      4318/node-red   
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::8080                 :::*                    LISTEN      -               
tcp6       0      0 :::80                   :::*                    LISTEN      -               
tcp6       0      0 :::5555                 :::*                    LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               
tcp6       0      0 :::8443                 :::*                    LISTEN      -               
tcp6       0      0 :::1883                 :::*                    LISTEN      - 
```

**Comment by hardillb** [comment]
Try with the firewall turned totally off.

The response from the WeMo devices might not be on port 1900 so there is no easy way to work out what ports to open up.

**Comment by glynhudson** [comment]
Yah! It worked with UFW turned off 👍 

Now discovery has happened can I turn the firewall back on? What ports are required for operation?

**Comment by hardillb** [comment]
If you turn it back on you'll have to turn it off again every time you restart Node-RED or do a full redeploy. There is also a background task that does discovery every 5mins to ensure that if the IP address or port of the WeMo device changes (the port tends to change if the device falls off the networks at all).

I've not found any combination of firewall rules that works, the discovery protocol looks to be once that needs a stateful firewall to track

**Comment by hardillb** [comment]
FYI for the next person to find this - http://git.netfilter.org/conntrack-tools/commit/?id=92246dcc1fdcf222302a42926e0e95af2c30463e will be needed if you want to run any sort of firewall on Linux. (I have not got this to build on Ubuntu 12.04, let alone run)

**Comment by xaos11** [comment]
I noticed this issue when running node-red on both raspbian and dietpi. Not running any firewall that I know of (no UFW), and on raspbian iptables is not configured. I don't have any genuine wemo device, but it doesn't seem to want to discover my "ESPurna" with fauxmo, nor my "test" device from the recently released node-red Alexa bridge skill. I am fine with using MQTT to control the ESPurna, but I just wonder, what could I be doing wrong? Upnp is enabled on the router and Alexa has no problem controlling either of the "devices".

**Comment by hardillb** [comment]
No devices created by for the Node-RED  Alexa Home Skill Bridge will ever be discoverable locally by the Wemo nodes, it's just not how it works.

As for the ESPurna, I've not heard of them, the WeMo nodes look for the BasicEvent ("urn:Belkin:service:basicevent:1") UPnP selector so if the device doesn't respond to that urn then it will not be discovered.

Also this repository is now closed, the code has been merged with the node-red-nodes-wemo in http://github.com/node-red/node-red-nodes repo
