### ISSUE TITLE
Get "Error: Node not deployed" when trying to switch socket

### ISSUE THREAD

**Issue by Roaders** [hardillb/node-red-contrib-wemo-ng#6]
This is most likely because I have not installed this correctly.

When I run node-red I get a couple of messages in the console:

Waiting for missing types to be registered:
- WeMoNG-dev
- WeMoNG out

Which is probably related.

How do I register these? I installed by unzipping the lib into the nodes folder then running npm install in the unzipped folder.

**Comment by hardillb** [comment]
If you run node-red with the `-v` command line argument does it give any more information?

When installing npm modules from src it is normally better to use the git repo syntax, but it shouldn't make a difference in this case.

npm install hardillb/node-red-contrib-wemo-ng

**Comment by Roaders** [comment]
I wasn't familiar with that syntax. Is that pulling it directly from github then or from a private npm account of yours or something.

Working fine now, no errors and I can control my WeMo lights along with my Hue. Fantastic!

Now on to getting my flics working with my new Raspberry Pi. Thanks for all your work on this.
