### ISSUE TITLE
Wemo Insight : unhandled wemo event type

### ISSUE THREAD

**Issue by bistory** [hardillb/node-red-contrib-wemo-ng#7]
Hi !

First thanks for this tool, I'm trying to make it work with my wemo insight switches :+1: 
I noticed than when I deploy, I get this message in the console :

`unhandled wemo event type
{ EnergyPerUnitCost: [ '6|200|4' ] }`

Do you have any clue on how this could be fixed ?

Thank you !

**Comment by hardillb** [comment]
It's not a problem, it's just a reminder that at some point I should do something with useful those messages. If you really don't like them you can always comment out line 329 in lib/wemo.js
