### ISSUE TITLE
No output from Wemo Insight 

### ISSUE THREAD

**Issue by glynhudson** [hardillb/node-red-contrib-wemo-ng#9]
I have successfully connected the flow to my Insight plug, I expected to see a perodic output message reporting it's state and power value. I have waited a few house and no output is to be seen: 

![node red emonpi](https://cloud.githubusercontent.com/assets/758844/15634487/e9a9d414-25bc-11e6-8863-1db47932d031.png)

Am I missing anything? How can I read the power value from my Insight Plug?

**Comment by hardillb** [comment]
Make sure you are using the node-red-node-wemo version rather than this repo.

But you should only really see messages when the state changes (on/off or crossing the power threshold)

**Comment by glynhudson** [comment]
Got it! Thanks, changing the state did the trick 👍 

Is there anyway to poll unit unit regularly to obtain power value without having to change state? I am interesting it getting the data into [Emoncms.org](https://emoncms.org).

**Comment by hardillb** [comment]
No, the polling was removed with this version in favour of the event mechanism
